/*
 * Copyright (c) 2018 by datagear.org.
 */

package org.datagear.persistence.features;

import org.datagear.model.PropertyFeature;
import org.datagear.model.support.MU;
import org.datagear.persistence.PersistenceFeature;

/**
 * 数据库自动生成。
 * <p>
 * 它可用于如下场景：
 * </p>
 * <ul>
 * <li>单元（{@linkplain MU#isSingleProperty(Property)}）、基本（
 * {@linkplain MU#isPrimitiveProperty(Property)}）属性：
 * <p>
 * 表示此属性的列值在插入时由数据库自动生成。
 * </p>
 * </li>
 * </ul>
 * 
 * @author datagear@163.com
 *
 */
public interface AutoGenerated extends PropertyFeature, PersistenceFeature
{

}
