CREATE TABLE T_ANALYSIS
(
	NAME VARCHAR(50),
	VAL_INTEGER INTEGER,
	VAL_REAL REAL
);

CREATE TABLE T_AUTO_GENERATED_KEYS
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(200),
	CREATE_TIME VARCHAR(200)
);
